// <auto-generated />
namespace FlowerPower.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DB1337 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DB1337));
        
        string IMigrationMetadata.Id
        {
            get { return "201806061401430_DB1337"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
